### ISSUE TITLE
IPv6 Full routing setup with ndppd

### ISSUE THREAD

**Issue by fr33m0nk** [finzzz/wgzero#8]
Hi,

First of all, this is a brilliant configuration tool and I am really thankful this exists.

I have recently purchased a VPS with [Wired Blade](https://www.wiredblade.com). The offer a routed IPv6 /64 subnet block with the VPS.

I then installed Debian 11 with wiregaurd and other prerequisites mentioned in Readme.
I then ran `wgzero install` with IPv6 along with full routing and ndppd.

My `ip a` output:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:xx:xx:xx:xx:xx brd ff:xx:xx:xx:xx:xx
    altname enp0s3
    inet 14x.xxx.xxx.xx/26 brd 14x.xxx.xxx.xx scope global ens3
       valid_lft forever preferred_lft forever
    inet6 26xx:xxx:xxxx:xx:bd::1/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe86:ad36/64 scope link 
       valid_lft forever preferred_lft forever
10: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.10.0.1/24 scope global wg0
       valid_lft forever preferred_lft forever
    inet6 26xx:xxx:xxxx:xx:bd::efe4/80 scope global 
       valid_lft forever preferred_lft forever
```

My server profile
```
[Interface]
Address = 10.10.0.1/24, 26xx:xxx:xxxx:xx:bd::efe4/80
SaveConfig = false
PrivateKey = <some key>
ListenPort = 17257
PostUp = /xxxx/postup.sh FR
PostDown = /xxxx/postdown.sh FR

# prashantmbp
[Peer]
PublicKey = <client public key>
AllowedIPs = 10.10.0.2/32, 26xx:xxx:xxxx:xx:bd::a271/128
```
My sysctl.conf:
```
net.ipv4.ip_forward=1
net.ipv6.conf.default.disable_ipv6=0
net.ipv6.conf.all.disable_ipv6=0
net.ipv6.conf.all.forwarding=1
net.ipv6.conf.all.accept_ra=1
net.ipv6.conf.default.forwarding=1
```
My client profile:
```
[Interface]
Address = 10.10.0.2/32, 26xx:xxx:xxxx:xx:bd::a271/128
PrivateKey = <client private key>
DNS = 2606:4700:4700::1111, 1.1.1.1 #Cloudflare DNS

[Peer]
PublicKey = <client public key>
Endpoint = 14x.xxx.xxx.xx:30525
AllowedIPs = 0.0.0.0/0, ::/0
```

ping6 works from client to Wiregaurd server after connecting VPN:
```
ping6 26xx:xxx:xxxx:xx:bd::efe4  
PING6(56=40+8+8 bytes) 26xx:xxx:xxxx:xx:bd::a271 --> 26xx:xxx:xxxx:xx:bd::efe4
16 bytes from 26xx:xx:xxxx:xx:bd::efe4, icmp_seq=0 hlim=64 time=349.761 ms
16 bytes from 26xx:xxx:xxxx:xx:bd::efe4, icmp_seq=1 hlim=64 time=370.677 ms
```

My PostUp rules:
```
#! /usr/bin/env bash

# ipv4
/usr/sbin/iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE

# ipv6
if [ "$1" == "NAT" ]; then
    /usr/sbin/ip6tables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
elif [ "$1" == "FR" ]; then
    /usr/sbin/ip6tables -A FORWARD -i wg0 -j ACCEPT ; ip6tables -A FORWARD -o wg0 -j ACCEPT
fi
```

however, ping6 to `ipv6.whatismyv6.com  ` fails
```
ping6 -c1 ipv6.whatismyv6.com    
PING6(56=40+8+8 bytes) 26xx:xxx:xxxx:xx:bd::a271 --> 2001:4838:0:1b::201

--- ipv6.whatismyv6.com ping6 statistics ---
1 packets transmitted, 0 packets received, 100.0% packet los
```

A few pointers on what could be going wrong would be great.

**Comment by finzzz** [comment]
Hello,

I'm trying to figure out what's happening, can you do a quick check and do `curl -6 https://ifconfig.co` from client as well as server?

**Comment by fr33m0nk** [comment]
Hi @finzzz,

From server:
`curl -6 https://ifconfig.co` results in `26xx:xxx:xxxx:xx:bd::1`
Same for `curl -6 http://ifconfig.co` resulting in `26xx:xxx:xxxx:xx:bd::1`

However from client, `curl -6` complains
```
curl -6 https://ifconfig.co
curl: (7) Failed to connect to ifconfig.co port 443: Network is unreachable

curl -6 http://ifconfig.co 
curl: (7) Failed to connect to ifconfig.co port 80: Network is unreachable
```

Following is the `/etc/ndppd.conf` contents:
```
proxy ens3 {
    timeout 500
    ttl 16000
    rule 26xx:xxx:xxxx:xx:bd::/64 {
        static
    }
} 
```

**Comment by finzzz** [comment]
What if you edit ndppd.conf to /80 like so:
```
proxy ens3 {
    timeout 500
    ttl 16000
    rule 26xx:xxx:xxxx:xx:bd::/80 {
        static
    }
}
```
And restart ndppd. Will you able to connect?

**Comment by fr33m0nk** [comment]
I updated `/etc/ndppd.conf` and restarted nipped using `sudo systemctl status ndppd`.
The logs came as following:
```
Feb 09 08:18:59 node99t-364.vps.wiredblade.com systemd[1]: Starting LSB: NDP Proxy Daemon...
Feb 09 08:18:59 node99t-364.vps.wiredblade.com ndppd[486]: (notice) ndppd (NDP Proxy Daemon) version 0.2.4
Feb 09 08:18:59 node99t-364.vps.wiredblade.com ndppd[486]: (notice) Using configuration file '/etc/ndppd.conf'
Feb 09 08:18:59 node99t-364.vps.wiredblade.com ndppd[486]: (warning) Low prefix length (80 <= 120) when using 'static' method
Feb 09 08:18:59 node99t-364.vps.wiredblade.com systemd[1]: Started LSB: NDP Proxy Daemon.
```

I was still not able to `ping6 ipv6.google.com` from the client. As was the case before, I could ping6 Wiregaurd server.
```
ping6 ipv6.google.com
PING6(56=40+8+8 bytes) 26xx:xxx:xxxx:xx:bd::a271 --> 2607:f8b0:4007:814::200e

--- ipv6.l.google.com ping6 statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
```

I also wanted to add that after connecting Wiregaurd client when I check my IP info using [ShowMyIP](https://www.showmyip.com), IPv6 allocated by Wiregaurd does not show up and is reported not detected. IPv4 of Wiregaurd VPS shows up correctly though.

When I disconnect Wiregaurd and refresh the page both, IPv4 and IPv6 as allocated by my ISP show up just fine.

**Comment by finzzz** [comment]
Looks like the packet is not being forwarded to WAN. Sorry, please return /80 back to /64, restart ndppd. And run `/usr/sbin/ip6tables -t nat -A POSTROUTING -o ens3 -j MASQUERADE` . Maybe that is missing, I'll try to reproduce the issue if this doesn't work.

**Comment by fr33m0nk** [comment]
Vincent, 
`/usr/sbin/ip6tables -t nat -A POSTROUTING -o ens3 -j MASQUERADE` works. I can use `ping6` at client and get response, but now the client has the IPv6 of VPS per [ShowMyIP](https://www.showmyip.com/), and not the one assigned to peer in Wiregaurd config.
 
Correct me if am wrong but wouldn't using `/usr/sbin/ip6tables -t nat -A POSTROUTING -o ens3 -j MASQUERADE` essentially introduce `NAT6` and defeat the purpose of having a routed IPv6 /64 subnet block as this does not use full IPv6 routing any more?

**Comment by finzzz** [comment]
Yes you're right. But this proves that the problem with previous configuration, is because client's packet is not routed outside. I think it is because you assign /64 to the main interface, I remember that it mustn't be assigned. You can easily get this work by getting full /64 address from https://ipv6.he.net/ though. But I'll try reproduce the issue tomorrow and update the docs.

**Comment by fr33m0nk** [comment]
Sure Vincent.
It would also be great if you can share the `/etc/network/interfaces` file contents of the machine using full IPv6 routing.
This will reaffirm the fact that IPv6 assignment to the interface needs to be changed, from `26xx:xxx:xxxx:xx:bd::1/64` to only `26xx:xxx:xxxx:xx:bd::1`.

**Comment by finzzz** [comment]
Hello, I found the solution, in your `/etc/network/interfaces` , set ens3 main address to `26xx:xxx:xxxx:xx:fafa::1/80` and reboot the host. See the last part of updated wiki.

backlinking issue #5

**Comment by fr33m0nk** [comment]
Apologies for the delay. I got in touch with my VPS provider and they told me that I only have `/80` IPv6 subnet allocated :| 
I split the original 26xx:xxx:xxxx:xx:bd::/80 subnet into a bun of `/84`  subnets.
Then allocated `26xx:xxx:xxxx:xx:bd::/84` to `ens3` interface and   `26xx:xxx:xxxx:xx:bd:1000::/84` to wiregaurd.
How ever I still couldn't get IPv6 working.

`cat /etc/network/interfaces`
```

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto ens3
iface ens3 inet static
    address   14x.xxx.xxx.18
    netmask   255.255.255.192
    gateway   14x.xxx.xxx.1
    dns-nameservers 2001:4860:4860::8888 8.8.8.8 2620:119:35::35 208.67.222.222
iface ens3 inet6 static
    address   26xx:xxx:xxxx:xx:bd::1
    netmask   84
    gateway   26xx:xxx:xxxx:xx::1
    dns-nameservers 2001:4860:4860::8888 8.8.8.8 2620:119:35::35 208.67.222.222
```

`ip -6 a`
```

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 26xx:xxx:xxxx:50:bd::1/84 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe86:ad36/64 scope link 
       valid_lft forever preferred_lft forever
4: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 state UNKNOWN qlen 1000
    inet6 26xx:xxx:xxxx:xx:bd:1000:0:c13c/84 scope global 
       valid_lft forever preferred_lft forever
```

`cat /etc/ndppd.conf `
```

proxy ens3 {
    timeout 500
    ttl 16000
    rule 26xx:xxx:xxxx:xx:bd::/80 {
        static
    }
} 
```

`cat /etc/wireguard/wg0.conf`
```

[Interface]
Address = 10.10.0.1/24, 26xx:xxx:xxxx:xx:bd:1000::c13c/84
SaveConfig = false
PrivateKey = <some-key>
ListenPort = 23044
PostUp = /root/.wgzero/postup.sh FR
PostDown = /root/.wgzero/postdown.sh FR

# prashantmbp
[Peer]
PublicKey = <some-key>
AllowedIPs = 10.10.0.2/32, 26xx:xxx:xxxx:xx:bd:1000::f479/128
```

Do I need to add some IP route for `26xx:xxx:xxxx:xx:bd:1000::/84`?

**Comment by finzzz** [comment]
I think /etc/network/interfaces should be
```
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto ens3
iface ens3 inet static
    address   14x.xxx.xxx.18
    netmask   255.255.255.192
    gateway   14x.xxx.xxx.1
    dns-nameservers 2001:4860:4860::8888 8.8.8.8 2620:119:35::35 208.67.222.222 <<<< use ipv4 dns for ipv4 address
iface ens3 inet6 static
    address   26xx:xxx:xxxx:xx:bd:ZZZ::1 <<<< must be on different subnet than 26xx:xxx:xxxx:xx:bd:1000::/84
    netmask   84
    gateway   26xx:xxx:xxxx:xx::1 <<<<<<<< don't define this
    dns-nameservers 2001:4860:4860::8888 8.8.8.8 2620:119:35::35 208.67.222.222 <<<< also this one
```
It works without modifying ip route

**Comment by fr33m0nk** [comment]
I made the fixes to ` /etc/network/interfaces` as you had suggested and rebooted.

Removing `gateway` for `inet6` from `ens3`, made server lose IPv6 internet connectivity and ping6 stopped responding at server.
So I added it back, still couldn't make ping6 work from VPN peer.

My ` /etc/network/interfaces` now:

```
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto ens3
iface ens3 inet static
    address   1xx.xxx.xxx.18
    netmask   255.255.255.192
    gateway   1xx.xxx.xxx.1
    dns-nameservers 94.140.14.14 94.140.15.15

iface ens3 inet6 static
    address   26xx:xxx:xxxx:xx:bd:2000::1
    netmask   84
    gateway   26xx:xxx:xxxx:xx::1
    dns-nameservers 2a10:50c0::ad1:ff 2a10:50c0::ad2:ff

```

**Comment by finzzz** [comment]
Well, I don't think SLAAC works with subnet less than /64. Ndppd should get full /64. I have just tried my script on vultr vps, it works just fine. If you want to make it works without bothering with vps provider, you can get free ipv6 from hurricane electric (he.net). Just assign /48 to main interface, and /64 to ndppd.

**Comment by fr33m0nk** [comment]
I am really thankful to you for helping me out so much :))
 
It would be very helpful you please elaborate on the setup with HE a little:

I got  following allocated at HE.net

Server IPv4 Address: `6x.xxx.7.82`
Server IPv6 Address: `20xx:xxx:1f18:527::1`
Client IPv4 Address: `14x.xxx.xxx.18`
Cleint IPv6 Address: `20xx:xxx:1f18:527::2`

Along with above I also got:
Routed /64: `20xx:xxx:1f19:527::/64`
Routed /48: `20xx:xxx:xxxx::b42d/48`

~~Should I use the newly added `he-ipv6` interface for setting up VPN?~~
Ok, tried with `he-ipv6`, it didnt't work at all. No internet what so ever with this device. 
There's also a `sit` interface which shows up while `wgzero install`
Changed wg0.conf to `ens3`

Should I use `Routed /48` for Wiregaurd?
And add `Routed /64` to `ndppd.conf`?


`/etc/network/interfaces`
```
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto ens3
iface ens3 inet static
    address   14x.xxx.xxx.18
    netmask   255.255.255.19x
    gateway   14x.xxx.xxx.1
    dns-nameservers 94.140.14.14 94.140.15.15

iface ens3 inet6 static
    address   26xx:xxx:xxx:xxx:bd::1
    gateway   26xx:xxx:xxxx:50::1
    netmask   64
    dns-nameservers 2a10:50c0::ad1:ff 2a10:50c0::ad2:ff


auto he-ipv6
iface he-ipv6 inet6 v4tunnel
        address 20xx:xxx:1f18:527::2
        netmask 64
        endpoint 6x.xxx.7.82
        local 14x.xxx.xxx.18
        ttl 255
        gateway 20xx:xxx:1f18:527::1
```

`/etc/ndppd.conf`
```
proxy he-ipv6 {
    timeout 500
    ttl 16000
    rule 20xx:xxx:xx38::/64 {
        static
    }
}
```

`/etc/wireguard/wg0.conf`
```
[Interface]
Address = 10.10.0.1/24, 20xx:xxx:xxxx::b42d/48
SaveConfig = false
PrivateKey = UB9QAzMmOKOELMgI0//+XyZREaJzFxpbM6hjoysyEXc=
ListenPort = 45009
PostUp = /root/.wgzero/postup.sh FR
PostDown = /root/.wgzero/postdown.sh FR
```

**Comment by finzzz** [comment]
Before you tweak wgzero, can you make sure that the host has ipv6 from tunnelbroker and can connect to ipv6 sites (don't use /64 address)? 

/48 should go to main interface and again, /64 shouldn't be assigned. wg0 should get 20xx:xxx:xx38::xxx/64, ndppd entry looks fine to me.

**Comment by fr33m0nk** [comment]
Thanks a lot Vincent for being patient with this.
Things are working with HE tunnel broker provided /48 and /64 subnets :))
I am closing this issue.

**Comment by finzzz** [comment]
Glad you solved the issue
