### ISSUE TITLE
How to distribute public ipv6 to the openwrt clients over wireguard using hurricane electric /48 ?

### ISSUE THREAD

**Issue by st1905** [finzzz/wgzero#9]
I want to use full routing via hurricane electric`s /48 but i`m not sure how to create the wireguard and openwrt configuration, i tried to randomly select /64 out of /48 and assigned /64 to wireguard interface and /64 to the openwrt as client but then i was not able to assign public ipv6 to the openwrt clients. Any help is much appreciated. 

with route48.org  i can just create the openwrt config like this https://otus.aug.is/route48-openwrt-wireguard

But i want to use my own vps to have hurricane electric`s network.

**Comment by finzzz** [comment]
How does openwrt find wg address? Is it through HE ipv6 or public ipv4? Can you show me a diagram of your ideal setup?

**Comment by st1905** [comment]
It finds thru ip4 of the VPS(i have cgnat) I tried to copy the same tutorial from the route48 setup, i assigned /64 for wireguard from the /48 i got from he. Openwrt gets the public v6, can ping and can access it from outside, connected clients also get the v6 addresses (They are within the /64 as well) but they simply don`t work.

**Comment by finzzz** [comment]
I can't help without a diagram. This is an advanced setup, you need to understand what is the tutorial is trying to do and what are you trying to achieve. Saying things like "they simply don`t work" is not helpful at all. Feel free to open this issue when you have the time to write detailed explanation with a diagram.
